/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AsyncErrorBoundary: typeof import('./src/components/common/AsyncErrorBoundary.vue')['default']
    ErrorBoundary: typeof import('./src/components/common/ErrorBoundary.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Pagination: typeof import('./src/components/common/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskFilters: typeof import('./src/components/tasks/TaskFilters.vue')['default']
    TaskForm: typeof import('./src/components/tasks/TaskForm.vue')['default']
    TaskList: typeof import('./src/components/tasks/TaskList.vue')['default']
  }
}
